name: Reusable workflow - test
on:
    workflow_call:
        inputs:
            SLACK_CHANNEL:
                description: "channel for reports"
                required: true
                type: string
            TEST_CONFIG_FILENAME:
                description: "config for test"
                required: true
                type: string
            YANDEX_AUTH_TOKEN:
                description: "token for authed and non payed account"
                required: true
                type: string
        secrets:
            MY_GITHUB_TOKEN:
                description: "token for access to current repo"
                required: true
            SLACK_TOKEN:
                description: "token for access message api"
                required: true
            PROXY_PASSWORD:
                description: "password for proxy"
                required: true
jobs:
    test:
        name: test
        runs-on: [ubuntu-latest]
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout current repo
              uses: actions/checkout@v2

            - name: Checkout testing repo
              uses: actions/checkout@v2
              with:
                  repository: Zebrainy/e2e-yandex-landing-script
                  path: ./testing

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"

            - name: Install yarn
              run: npm install -g yarn

            - name: Copy based snapshots folder
              shell: bash
              run: |
                  cp -R app_snapshots ./testing/  2>/dev/null || :

            - name: Convert config to string
              id: convert-config
              run: |
                  echo "TEST_CONFIG=$(cat ${{ inputs.TEST_CONFIG_FILENAME }} | tr -d '\n')" >> $GITHUB_OUTPUT

            - name: Install dependencies
              working-directory: ./testing
              run: |
                  yarn

            - name: Run tests
              id: run_test
              working-directory: ./testing
              run: |
                  yarn cross-env CONFIG_PATH=$GITHUB_WORKSPACE/${{ inputs.TEST_CONFIG_FILENAME }} YANDEX_TOKEN='${{ inputs.YANDEX_AUTH_TOKEN }}' PROXY_PASSWORD='${{secrets.PROXY_PASSWORD}}' yarn test
                  
            - name: Copy updated snapshots back
              if: ${{ !cancelled() && steps.run_test.outcome == 'failure' }}
              run: |
                  pushd ./testing/app_snapshots/
                  touch ../newFiles

                  # добавляет "новые скриншоты" в base и записывает их в файл newFiles для дальнейшего логирования в мессенджер
                  # новые скриншоты это те, которые есть в папке received, но нет в папке base
                  for f in ./*/received/*; do
                    newPath=$(echo "$f" | sed s/received/base/);
                    echo "new path: $newPath"
                    [[ -d $(dirname $newPath) ]] || (mkdir -p $(dirname $newPath) && cp -p "$f" "$newPath" && echo $f >> ../newFiles);
                  done

                  cat ../newFiles
                  echo "test"

                  ls -R 
                  echo "end"
                  # копирует все скриншоты из папки received, для которых есть diff, в папку base
                  for f in ./diff/*/*; do
                    hash=$(basename "$(dirname $f)");
                    receivedPath=$(echo ./$hash/received);
                    basePath=$(echo "$receivedPath" | sed s/received/base/)
                    cp $receivedPath/* $basePath
                  done
                  
                  cp -R . $GITHUB_WORKSPACE/app_snapshots/  2>/dev/null || :

            - name: Copy config map
              if: ${{ !cancelled() && steps.run_test.outcome == 'failure'}}
              run: |
                  cp ./testing/test_config.map.json ./

            - name: Clear unused sties
              if: ${{ always() }} 
              run: |
                  pushd ./testing/
                  yarn clear-unused-sites

              
            - name: Get current branch name
              if: ${{ !cancelled() && steps.run_test.outcome == 'failure'}}
              id: get_branch_name
              run: echo "CURRENT_BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT

            - name: Create pull request
              if: ${{  !cancelled() && steps.run_test.outcome == 'failure' }}
              uses: peter-evans/create-pull-request@v3
              id: pull-request
              with:
                  token: ${{ secrets.MY_GITHUB_TOKEN }}
                  commit-message: "Update snapshots"
                  title: "Add new base snapshots"
                  body: "Update snapshots"
                  committer: GitHub <noreply@github.com>
                  author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                  branch: "update-snapshots"
                  delete-branch: true
                  base: ${{ steps.get_branch_name.outputs.CURRENT_BRANCH }}
                  add-paths: |
                      ./app_snapshots/**/base/*
                      ./test_config.map.json

            - name: Handle result
              id: handle-result
              if: ${{ !cancelled() && steps.run_test.outcome == 'failure' }}
              run: |
                  pushd ./testing/

                  export PULL_REQUEST_URL="${{ steps.pull-request.outputs.pull-request-url }}"
                  export SLACK_TOKEN=${{ secrets.SLACK_TOKEN }}
                  export SLACK_CHANNEL=${{ inputs.SLACK_CHANNEL }}
                  export GITHUB_ACTION_URL="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"

                  # если количество файлов в папке diff больше 0
                  if [ $(ls ./app_snapshots/diff  2>/dev/null | wc -l) -gt 0 ];
                  then
                      yarn report-diff 
                      yarn report-new
                  elif [ "$PULL_REQUEST_URL" != "" ]
                  then
                      yarn report-new
                  else
                      yarn report-errors
                  fi
