name: Reusable workflow - test
on:
    workflow_call:
        inputs:
            SLACK_CHANNEL:
                description: "channel for reports"
                required: true
                type: string
            TEST_CONFIG_FILENAME:
                description: "config for test"
                required: true
                type: string
            YANDEX_AUTH_TOKEN:
                description: "token for authed and non payed account"
                required: true
                type: string
        secrets:
            MY_GITHUB_TOKEN:
                description: "token for access to current repo"
                required: true
            SLACK_TOKEN:
                description: "token for access message api"
                required: true

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout current repo
              uses: actions/checkout@v2

            - name: Checkout testing repo
              uses: actions/checkout@v2
              with:
                  repository: Zebrainy/e2e-yandex-landing-script
                  path: ./testing

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"

            - name: Install yarn
              run: npm install -g yarn

            - name: Check for first run
              run: echo "IS_FIRST_RUN=$([ -d "app_snapshots" ] && echo "false" || echo "true" )" >> $GITHUB_ENV

            - name: Copy based snapshots folder
              shell: bash
              run: |
                  cp -R app_snapshots ./testing/  2>/dev/null || :

            - name: Convert config to string
              id: convert-config
              run: |
                  echo "TEST_CONFIG=$(cat ${{ inputs.TEST_CONFIG_FILENAME }} | tr -d '\n')" >> $GITHUB_OUTPUT

            # - name: Get yarn cache directory path
            #   working-directory: ./testing
            #   id: yarn-cache-dir-path
            #   run: echo "::set-output name=dir::$(yarn cache dir)"

            # - uses: actions/cache@v2
            #   id: yarn-cache
            #   with:
            #       path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
            #       key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            #       restore-keys: |
            #           ${{ runner.os }}-yarn-

            - name: Install dependencies
              working-directory: ./testing
              run: |
                  yarn

            - name: Run tests
              id: run_test
              working-directory: ./testing
              run: |
                  yarn cross-env CONFIG_PATH=$GITHUB_WORKSPACE/${{ inputs.TEST_CONFIG_FILENAME }} YANDEX_TOKEN='${{ inputs.YANDEX_AUTH_TOKEN }}' yarn test

            - name: Copy updated snapshots back
              if: ${{ env.IS_FIRST_RUN == 'true' || ( !cancelled() && steps.run_test.outcome == 'failure')}}
              run: |
                  pushd ./testing/app_snapshots/
                  rm -rf ./**/base
                  for f in ./**/received; do mv "$f" "$(echo "$f" | sed s/received/base/)"; done
                  cp -R . $GITHUB_WORKSPACE/app_snapshots/  2>/dev/null || :

            - name: Get current branch name
              if: ${{ env.IS_FIRST_RUN == 'true' || ( !cancelled() && steps.run_test.outcome == 'failure')}}
              id: get_branch_name
              run: echo "CURRENT_BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT

            - name: Create pull request
              if: ${{ env.IS_FIRST_RUN == 'true' || ( !cancelled() && steps.run_test.outcome == 'failure')}}
              uses: peter-evans/create-pull-request@v3
              id: pull-request
              with:
                  token: ${{ secrets.MY_GITHUB_TOKEN }}
                  commit-message: "Update snapshots"
                  title: "Add new base snapshots"
                  body: "Update snapshots"
                  committer: GitHub <noreply@github.com>
                  author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                  branch: "update-snapshots"
                  delete-branch: true
                  base: ${{ steps.get_branch_name.outputs.CURRENT_BRANCH }}
                  add-paths: |
                      ./app_snapshots/**/base/*

            - name: Prepare result
              id: prepare-result
              if: ${{ env.IS_FIRST_RUN == 'true' || ( !cancelled() && steps.run_test.outcome == 'failure')}}
              run: |
                  pushd ./app_snapshots/
                  rm -rf ./**/received
                  rm -rf ./**/base
                  zip -r screenshot-diffs.zip *

            - name: Send report in slack if first run
              if: ${{ env.IS_FIRST_RUN == 'true' }}
              uses: Zebrainy/slack-send@v1
              id: send-message-first-run
              with:
                  MESSAGE_TEXT: |
                      :white_check_mark: Первый запуск тестов прошёл успешно. Скриншоты сгенерированы и отправлены ${{ format('<{0}|пулл реквестом>', steps.pull-request.outputs.pull-request-url) }}
                  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
                  CHANNELS: ${{ inputs.SLACK_CHANNEL }}

            - name: Send report in slack if diff found
              if: ${{  !cancelled() && steps.run_test.outcome == 'failure'}}
              uses: Zebrainy/slack-send@v1
              id: send-message-fail
              with:
                  MESSAGE_TEXT: |
                      :smiling_face_with_tear: Упс, тест упал, но мы уже создали ${{ format('<{0}|пулл реквест>', steps.pull-request.outputs.pull-request-url) }} с новыми скриншотами, проверьте его и, если все ок, то смержите.
                      (<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|action>)

                  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
                  FILENAME: ./app_snapshots/screenshot-diffs.zip
                  CHANNELS: ${{ inputs.SLACK_CHANNEL }}
